#!/bin/sh

CRYPTREST_LETSENCRYPT_NAME='letsencrypt'
CRYPTREST_LETSENCRYPT_GIT_BRANCH="${CRYPTREST_LETSENCRYPT_GIT_BRANCH:=master}"
CRYPTREST_LETSENCRYPT_GIT_URL="https://github.com/$CRYPTREST_LETSENCRYPT_NAME/$CRYPTREST_LETSENCRYPT_NAME/archive/$CRYPTREST_LETSENCRYPT_GIT_BRANCH.tar.gz"
CRYPTREST_LETSENCRYPT_OPT_DIR="$CRYPTREST_OPT_DIR/$CRYPTREST_LETSENCRYPT_NAME"
CRYPTREST_LETSENCRYPT_ETC_DIR="$CRYPTREST_ETC_DIR/$CRYPTREST_LETSENCRYPT_NAME"
CRYPTREST_LETSENCRYPT_ETC_ENV_FILE="$CRYPTREST_LETSENCRYPT_ETC_DIR/.env"
CRYPTREST_LETSENCRYPT_CERTBOT_DIR="$CRYPTREST_LETSENCRYPT_OPT_DIR/certbot-$CRYPTREST_LETSENCRYPT_GIT_BRANCH"
CRYPTREST_LETSENCRYPT_BIN_FILE="$CRYPTREST_BIN_DIR/cryptrest-$CRYPTREST_LETSENCRYPT_NAME"

CRYPTREST_LETSENCRYPT_URL="https://$CRYPTREST_LETSENCRYPT_NAME.org/certs/"
CRYPTREST_LETSENCRYPT_PEM_FILES='lets-encrypt-x4-cross-signed.pem lets-encrypt-x3-cross-signed.pem isrgrootx1.pem'
CRYPTREST_LETSENCRYPT_TITLE="Let's Encrypt"


letsencrypt_prepare()
{
    rm -rf "$CRYPTREST_LETSENCRYPT_OPT_DIR" && \
    rm -rf "$CRYPTREST_LETSENCRYPT_ETC_DIR" && \
    rm -rf "$CRYPTREST_LETSENCRYPT_CERTBOT_DIR" && \
    [ -d "$CRYPTREST_BIN_DIR/" ] && \
    rm -f "$CRYPTREST_LETSENCRYPT_BIN_FILE"*
}

letsencrypt_download()
{
    mkdir -p "$CRYPTREST_LETSENCRYPT_OPT_DIR" && \
    cd "$CRYPTREST_LETSENCRYPT_OPT_DIR" && \
    curl -SL "$CRYPTREST_LETSENCRYPT_GIT_URL" | tar -xz
    if [ $? -ne 0 ]; then
        echo "Some error with download"
        rm -rf "$CRYPTREST_LETSENCRYPT_OPT_DIR"

        exit 1
    fi
}

letsencrypt_install()
{
    mkdir -p "$CRYPTREST_LETSENCRYPT_ETC_DIR" && \
    chmod 700 "$CRYPTREST_LETSENCRYPT_ETC_DIR" && \
    chmod 700 "$CRYPTREST_LETSENCRYPT_CERTBOT_DIR" && \
    chmod 700 "$CRYPTREST_LETSENCRYPT_OPT_DIR"
}

letsencrypt_define()
{
    cp "$CRYPTREST_MODULES_DIR/$CRYPTREST_LETSENCRYPT_NAME/opt/"*.sh "$CRYPTREST_LETSENCRYPT_OPT_DIR/" && \
    chmod 400 "$CRYPTREST_LETSENCRYPT_OPT_DIR/"*.sh && \
    ln -s "$CRYPTREST_LETSENCRYPT_CERTBOT_DIR/certbot-auto" "$CRYPTREST_LETSENCRYPT_BIN_FILE" && \
    chmod 500 "$CRYPTREST_LETSENCRYPT_BIN_FILE" && \

    echo "# $CRYPTREST_LETSENCRYPT_TITLE" > "$CRYPTREST_LETSENCRYPT_ETC_ENV_FILE"
    echo "CRYPTREST_LETSENCRYPT_URL=\"$CRYPTREST_LETSENCRYPT_URL\"" >> "$CRYPTREST_LETSENCRYPT_ETC_ENV_FILE"
    echo "CRYPTREST_LETSENCRYPT_PEM_FILES=\"$CRYPTREST_LETSENCRYPT_PEM_FILES\"" >> "$CRYPTREST_LETSENCRYPT_ETC_ENV_FILE"
    chmod 400 "$CRYPTREST_LETSENCRYPT_ETC_ENV_FILE" && \

    echo ''
    echo "CRYPTREST_LETSENCRYPT_* variables added in '$CRYPTREST_LETSENCRYPT_ETC_ENV_FILE'"
    echo ''
}


echo ''
echo "$CRYPTREST_LETSENCRYPT_TITLE branch: $CRYPTREST_LETSENCRYPT_GIT_BRANCH"
echo "$CRYPTREST_LETSENCRYPT_TITLE URL: $CRYPTREST_LETSENCRYPT_GIT_URL"
echo ''

letsencrypt_prepare && \
letsencrypt_download && \
letsencrypt_install && \
letsencrypt_define
